-- Create Machines Table in Supabase
create table machines (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  materials text,
  max_pressure float,
  hourly_rate int,
  status text default 'IDLE',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table machines enable row level security;

-- Create policy to allow all access (for MVP simplicity, adjust for prod)
create policy "Enable all access for all users" on machines for all using (true) with check (true);
